Claw:
  Ports:
    liftVertical: 3
    liftRotation: 4
    verticalTicks: [1, 2]
    rotationAngle: {Channel: 1, Scale: 5.0, Offset: 0.0}
    clampOne: [1, 1]
    clampOne: [1, 2]
    rollers: 1
    button: 1
  Software:
    LiftAngle: 
      min: 90
      max: 270
    LiftHeight:
      min: 1
      max: 1
    clearClaw:
      min: 0.0
      max: 5.0
  Speeds: # assuming -1.0 spits things out
    outward: 1.0
    inward: 1.0
    forwardRotation: 0.5
    backwardRotation: 0.5
Drive:
  drive:
    L: 2
    R: 0
  encoder:
    L: [0, 1]
    R: [2, 3]
  PID:
    L: {P: 0.02, I: 0, D: 0, F: 0}
    R: {P: 0.02, I: 0, D: 0, F: 0}
  maxRPS: 30
Shuttle:
  Ports:
    toteSensor: 1
    lowerLimit: 10
    upperLimit: 11
    clampPiston: [0, 1]
    lift:
      motor: 1
      encoder: 1
      pdp: 15
  Values:
    upSpeed: -0.1
    downSpeed: 0.1
    maxCurrent: 5.0
