Claw:
  Ports:
    clampOne: [6, 7]
    clampTwo: [8, 9]
    finger: [0, 1]
    rollers: 11
    button: 10
  Speeds: # assuming -1.0 spits things out
    outward: 1.0
    inward: 1.0
Drive:
  drive:
    L: 2
    R: 0
  encoder:
    L: [0, 1]
    R: [2, 3]
  PID:
    L: {P: 0.02, I: 0, D: 0, F: 0}
    R: {P: 0.02, I: 0, D: 0, F: 0}
  maxRPS: 30
Shuttle:
  Ports:
    toteSensor: 1
    lowerSensor: 1
    upperSensor: 1
    clampPiston: [1, 2]
    elevator: 1
