MessageCommand:
  - name: One
    message: Testing message for variant one
  - name: Two
    message: Testing message for variant two
DriveContinuous:
  joystick: 0
  axes:
    left: 1
    right: 3

HomeShuttle:

ShuttlePosition:
  - name: Down
    ticks: 0
  - name: Up
    ticks: 665

ShuttleClamp:
  - name: Open
  - name: Close

ClawClamp:
  - name: Released
    status: 0
  - name: Tote
    status: 1
  - name: Container
    status: 2
  - name: DeathGrip
    status: 3

ClawRotation:
  - name: InBot
    status: 145
    tolerance: 5.0
  - name: Platform
    status: 227.5
    tolerance: 1.5
  - name: Pick
    status: 80
    tolerance: 5.0

ClawRollers:
  - name: In
    status: 2
  - name: Out
    status: 1
  - name: Off
    status: 0

Fingers:
  - name: Hold
    state: 1
  - name: Release
    state: 0

RecieveTote:
  rollerSpeed: -.5

UnloadTote:
  - name: Barf
    rollerSpeed: 1
  - name:
    rollerSpeed: .5

FlapFlappers:
