###########
# TESTING #
###########

MessageCommand:
  - name: One
    message: Testing message for variant one
  - name: Two
    message: Testing message for variant two

#########
# DRIVE #
#########

DriveContinuous:
  joystick: 0
  axes:
    left: 1
    right: 3

DriveDistance:
  - name: AutoPick
    speed: 0.45
    distance: 1.0
  - name: AutoPickLong
    speed: 0.45
    distance: 4.0
  - name: AutoPickShort
    speed: 0.45
    distance: 1.0
  - name: AutoBack
    speed: -0.45
    distance: 7.0
  - name: AutoBackLong
    speed: -0.45
    distance: 8.0
  - name: AutoThreeDistance
    speed: 0.45
    distance: 8.0
  - name: AutoFourDistance
    speed: 0.45
    distance: 1.0

DriveRotate:
  - name: Test
    speed: .35
    angle: -90.0
    tolerance: .5
    rampAngle: 45.0
    rampFactor: .25

###########
# SHUTTLE #
###########

ArmShuttle:
  first:
    rollerSpeed: 0.8
    flapperSpeed: 0.35
  rest:
    rollerSpeed: 0.05
    flapperSpeed: 1.0
  bump:
    rollerSpeed: -.5
    flapperSpeed: 0
  toteTicks: 6
  bumpTime: .25

Fingers:
  - name: Hold
    state: 1
  - name: Release
    state: 0

HomeShuttle:
  # No config

LackOfStack:
  # No config

$Restack:
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttlePositionUnload
  - FingersRelease
  - name: WaitCommand
    time: 0
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

SetDesiredTotes:
  - name: Two
    number: 2
  - name: Three
    number: 3
  - name: Four
    number: 4
  - name: Five
    number: 5
  - name: Six
    number: 6

ShuttleClamp:
  - name: Open
  - name: Close

ShuttleDown:
  ticks: 50
  tolerance: 10
  speedMul: 0.0

ShuttleHold:
  speed: -.4
  time: .5

$ShuttleInit:
  - FingersRelease
  - ShuttleClampOpen
  - HomeShuttle

ShuttlePosition:
  - name: Down
    ticks: 0
  - name: Up
    ticks: 700
  - name: Unload
    ticks: 350
  - name: Unstack
    ticks: 460

ShuttleRamp:
  - name: Up
    ticks: 697
    tolerance: 5
    rampFactor: .75
    rampDistance: 300
  - name: Down
    ticks: 0
    tolerance: 5
    rampFactor: .2
    rampDistance: 300

$StackTote:
  - name: WaitCommand
    time: .25
  - FingersHold
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: .25
  - ShuttleRampUp
  - name: WaitCommand
    time: .25
  - ShuttleClampOpen
  - ShuttleRampDown
  - UpdateTotesRatcheted

ToteDirector:
  samples: 6

$Unstack:
  - ShuttleClampOpen
  - ShuttlePositionUnstack
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttleRampUp
  - FingersRelease
  - ShuttleHold
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

UpdateTotesRatcheted:
  # No config

########
# CLAW #
########

HomeClaw:
  speed: .4

TopClaw:
  speed: -1

ClawClamp:
  - name: Released
    status: 0
  - name: Tote
    status: 1
  - name: Container
    status: 2
  - name: DeathGrip
    status: 3

ClawClampToggle:
  # No config

ClawEstablishHome:
  # No config

ClawForceHome:
  angle: 69.0
  speed: -.25

ClawPosition:
  - name: Pick
    target: 0.0
    tolerance: 3.0
    speedMul: 1.0
  - name: Transport
    target: 30.0
    tolerance: 3.0
    speedMul: 1.0
  - name: Top
    target: 243.0
    tolerance: 3.0
    speedMul: 1.0
  - name: Middle
    target: 200
    tolerance: 3.0
    speedMul: 1.0
  - name: Platform
    target: 178
    tolerance: 3.0
    speedMul: .5
  - name: Regrip
    target: 156
    tolerance: 3.0
    speedMul: .5

ClawRamp:
  - name: Pick
    target: 0.0
    tolerance: 3.0
    speed: 1.0
    rampDistance: 50.0
    rampFactor: .25

ClawRegripPosition:
  speed: .2

ClawRollers:
  - name: In
    status: 2
  - name: Out
    status: 1
  - name: Off
    status: 0

ClawRotation:
  - name: Pick
    targetAngle: 0
  - name: Platform
    targetAngle: 1

ClawRotationContinuous:
  tolerance: 15.0
  angles: [70, 235] # Pick, Platform
  speeds: {move: .25, hold: .15}

ClawSmartRollers:
  waitTime: .25

ClawToHome:
  rotateWait: .25

$ClawToHome:
  - ClawRotationPick
  - name: WaitCommand
    time: 0.25
  - ClawPositionPick

$ClawToPick:
  - ClawRotationPick
  - ClawRampPick

$GroundToPlatform:
  - ClawPositionMiddle
  - ClawRotationPlatform
  - name: WaitCommand
    time: 0.5
  - ClawPositionPlatform

ManualClawLift:
  - name: "Up"
    speed: 1
  - name: "Down"
    speed: 2

$PickBin:
  - ClawClampTote
  - ClawSmartRollers
  - name: WaitCommand
    time: 0.25
  - ClawClampDeathGrip

$ClawPick:
  - $ClawToPick
  - $PickBin

$PickUpMoveToPlatform:
  - $PickBin
  - name: WaitCommand
    time: 0.25
  - $GroundToPlatform

$PlatformToPlacement:
  - ClawPositionTop
  - LackOfStack
  - ClawRotationPick

$RegripBin:
  - name: WaitCommand
    time: 0.50
  - ClawClampReleased
  - name: WaitCommand
    time: 0.25
  - ClawPositionRegrip
  - name: WaitCommand
    time: 0.25
  - ClawClampContainer
  - ClawSmartRollers
  - ClawClampDeathGrip

#############
# TOTE FEED #
#############

BumpBottomTote:
  rollerSpeed: -0.5
  time: 0.25

FlapFlappers:
  # No config

HoldBottomTote:
  rollerSpeed: 0.05

IntakeTotes:
  flapperSpeed: 1.0

RecieveBottomTote:
  flapperSpeed: 0.35
  rollerSpeed: 0.8

RollerbedPiston:
  - name: Up
    direction: 0
  - name: Down
    direction: 1

RollerbedPistonToggle:
  # No config

UnloadTote:
  rollerSpeed: -1
  flapperSpeed: -1

########
# AUTO #
########

$Auto0:
  # No commands

$Auto1:
  - name: DriveDistanceAutoPickLong
    execution: Parallel
  - $PickBin
  - $GroundToPlatform
  - $RegripBin

$Auto2:
  - name: DriveDistanceAutoPick
    execution: Parallel
  - $PickBin
  - name: DriveDistanceAutoBackLong
    execution: Parallel
  - $GroundToPlatform
  - $RegripBin

$Auto3:
  - name: DriveDistanceAutoThreeDistance
    execution: Parallel
  - $PickBin
  - $GroundToPlatform
  - $RegripBin

$Auto4:
  - name: DriveDistanceAutoFourDistance
    execution: Parallel
  - $PickBin
  - $GroundToPlatform
  - $RegripBin

$Auto5:
  - name: DriveDistanceAutoPickShort
    execution: Parallel
  - $PickBin
  - name: DriveDistanceAutoBack
    execution: Parallel
  - $GroundToPlatform
  - $RegripBin

$Auto6:
  - DriveRotateTest

###########
# UTILITY #
###########

Cancel:
  - name: ToteDirector
  - name: ClawForceHome
  - name: HomeClaw
