MessageCommand:
  - name: One
    message: Testing message for variant one
  - name: Two
    message: Testing message for variant two
DriveContinuous:
  joystick: 0
  axes:
    left: 1
    right: 3

HomeShuttle:

ShuttlePosition:
  - name: Down
    ticks: 100
  - name: Up
    ticks: 500

ShuttleClamp:
  - name: Open
  - name: Close

SetClaw:
  - name: Closed
    status: 0
  - name: Short
    status: 1
  - name: Mid
    status: 2
  - name: Long
    status: 3

ClawRotation:
  - name: InBot
    status: 90.0
  - name: Platform
    status: 0.0
  - name: Pick
    status: 180.0
