###########
# TESTING #
###########

MessageCommand:
  - name: One
    message: Testing message for variant one
  - name: Two
    message: Testing message for variant two

#########
# DRIVE #
#########

DriveContinuous:
  joystick: 0
  axes:
    left: 1
    right: 3

DriveDistance:
  - name: AutoPick
    speed: 0.45
    distance: 1.0
  - name: AutoPickLong
    speed: 0.45
    distance: 4.0
  - name: AutoPickShort
    speed: 0.45
    distance: 1.0
  - name: AutoBack
    speed: -0.45
    distance: 7.0
  - name: AutoBackLong
    speed: -0.45
    distance: 8.0
  - name: AutoThreeDistance
    speed: 0.45
    distance: 8.0
  - name: AutoFourDistance
    speed: 0.45
    distance: 1.0

DriveRotate:
  - name: Auto6
    speed: .75
    angle: -90.0
    tolerance: .5
    slowAngle: 25.0
    slowFactor: .4

DriveStraight:
  - name: Auto6
    speed: .75
    distance: 15.0
    speedOffset: .2
    angleTolerance: .25

###########
# SHUTTLE #
###########

ArmShuttle:
  first:
    rollerSpeed: 0.8
    flapperSpeed: 0.35
  rest:
    rollerSpeed: 0.05
    flapperSpeed: 1.0
  bump:
    rollerSpeed: -.5
    flapperSpeed: 0
  toteTicks: 6
  bumpTime: .25

Fingers:
  - name: Hold
    state: 1
  - name: Release
    state: 0

HomeShuttle:
  # No config

LackOfStack:
  # No config

$Restack:
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttlePositionUnload
  - FingersRelease
  - name: WaitCommand
    time: 0
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

SetDesiredTotes:
  - name: Two
    number: 2
  - name: Three
    number: 3
  - name: Four
    number: 4
  - name: Five
    number: 5
  - name: Six
    number: 6

ShuttleClamp:
  - name: Open
  - name: Close

ShuttleDown:
  ticks: 50
  tolerance: 10
  speedMul: 0.0

ShuttleHold:
  speed: -.4
  time: .5

$ShuttleInit:
  - FingersRelease
  - ShuttleClampOpen
  - HomeShuttle

ShuttlePosition:
  - name: Down
    ticks: 0
  - name: Up
    ticks: 700
  - name: Unload
    ticks: 350
  - name: Unstack
    ticks: 460

ShuttleRamp:
  - name: Up
    ticks: 697
    tolerance: 5
    rampFactor: .75
    rampDistance: 300
  - name: Down
    ticks: 0
    tolerance: 5
    rampFactor: .2
    rampDistance: 300

$StackTote:
  - name: WaitCommand
    time: .25
  - FingersHold
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: .25
  - ShuttleRampUp
  - name: WaitCommand
    time: .25
  - ShuttleClampOpen
  - ShuttleRampDown
  - UpdateTotesRatcheted

ToteDictator:
  samples: 6

$Unstack:
  - ShuttleClampOpen
  - ShuttlePositionUnstack
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttleRampUp
  - FingersRelease
  - ShuttleHold
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

UpdateTotesRatcheted:
  # No config

########
# CLAW #
########

HomeClaw:
  speed: .4

TopClaw:
  speed: -1

ClawClamp:
  - name: Released
    status: 0
  - name: Tote
    status: 1
  - name: Container
    status: 2
  - name: DeathGrip
    status: 3

ClawClampToggle:
  # No config

ClawEstablishHome:
  # No config

ClawRegripPosition:
  speed: .2

ClawRollers:
  - name: In
    status: 2
  - name: Out
    status: 1
  - name: Off
    status: 0

ClawSmartRollers:
  waitTime: .25

ClawToAngle:
  - name: Front
    angle: front
    speed: -.25
    holdSpeed: -.15
    minimumHeight: 160
  - name: Back
    angle: back
    speed: .25
    holdSpeed: .15
    minimumHeight: 160

ClawToHeight:
  - name: Home
    height: 0.0
    ramp: {distance: 50.0, factor: .15}
    speed: 1.0
    requiredAngle: front
  - name: Top
    height: 247.0
    ramp: {distance: 20.0, factor: .25}
    speed: 1.0
    requiredAngle: neither
  - name: Middle
    height: 200
    ramp: {distance: 0.0, factor: 0.0}
    speed: 1.0
    requiredAngle: neither
  - name: Platform
    height: 178
    ramp: {distance: 0.0, factor: 0.0}
    speed: .25
    requiredAngle: back
  - name: Regrip
    height: 156
    ramp: {distance: 0.0, factor: 0.0}
    speed: .25
    requiredAngle: back

ClawToHome:
  rotateWait: .25

$ClawToHome:
  - ClawToAngleFront
  - name: WaitCommand
    time: 0.25
  - ClawToHeightHome

$ClawToPick:
  - ClawToAngleFront
  - ClawToHeightHome

$GroundToPlatform:
  - ClawToHeightMiddle
  - ClawToAngleBack
  - name: WaitCommand
    time: 0.5
  - ClawToHeightPlatform

ManualClawLift:
  - name: "Up"
    speed: -.75
  - name: "Down"
    speed: .25

$PickBin:
  - ClawClampTote
  - ClawSmartRollers
  - name: WaitCommand
    time: 0.25
  - ClawClampDeathGrip

$ClawPick:
  - $ClawToPick
  - $PickBin

$PickUpMoveToPlatform:
  - $PickBin
  - name: WaitCommand
    time: 0.25
  - $GroundToPlatform

$PlatformToPlacement:
  - ClawToHeightTop
  - LackOfStack
  - ClawToAngleFront

$RegripBin:
  - name: WaitCommand
    time: 0.50
  - ClawClampReleased
  - name: WaitCommand
    time: 0.25
  - ClawToHeightRegrip
  - name: WaitCommand
    time: 0.25
  - ClawClampContainer
  - ClawSmartRollers
  - ClawClampDeathGrip

#############
# TOTE FEED #
#############

BumpBottomTote:
  rollerSpeed: -0.5
  time: 0.25

HoldBottomTote:
  rollerSpeed: 0.05

IntakeTotes:
  flapperSpeed: 1.0

RecieveBottomTote:
  flapperSpeed: 0.35
  rollerSpeed: 0.8

UnloadTote:
  rollerSpeed: -1
  flapperSpeed: -1

########
# AUTO #
########

$Auto0:
  # No commands

$Auto1:
  - name: DriveDistanceAutoPickLong
    execution: Parallel
  - $PickBin
  - $GroundToPlatform
  - $RegripBin

$Auto2:
  - name: DriveDistanceAutoPick
    execution: Parallel
  - $PickBin
  - name: DriveDistanceAutoBackLong
    execution: Parallel
  - $GroundToPlatform
  - $RegripBin

$Auto3:
  - name: DriveDistanceAutoThreeDistance
    execution: Parallel
  - $PickBin
  - $GroundToPlatform
  - $RegripBin

$Auto4:
  - name: DriveDistanceAutoFourDistance
    execution: Parallel
  - $PickBin
  - $GroundToPlatform
  - $RegripBin

$Auto5:
  - name: DriveDistanceAutoPickShort
    execution: Parallel
  - $PickBin
  - name: DriveDistanceAutoBack
    execution: Parallel
  - $GroundToPlatform
  - $RegripBin

$Auto6BinSequence:
  - $GroundToPlatform
  - $RegripBin

$Auto6DriveSequence:
  - DriveRotateAuto6
  - DriveStraightAuto6

$Auto6:
  - $PickBin
  - name: $Auto6BinSequence
    execution: Parallel
  - $Auto6DriveSequence

$Auto7:
  - DriveRotateAuto6

###########
# UTILITY #
###########
