MessageCommand:
  - name: One
    message: Testing message for variant one
  - name: Two
    message: Testing message for variant two
DriveContinuous:
  joystick: 0
  axes:
    left: 1
    right: 3

HomeShuttle:

ShuttlePosition:
  - name: Down
    ticks: 0
    tolerance: 10
  - name: Up
    ticks: 687
    tolerance: 10
  - name: Unload
    ticks: 400
    tolerance: 10

ShuttleDown:
  ticks: 50
  tolerance: 10
  speed: -.2

ShuttleClamp:
  - name: Open
  - name: Close

ClawClamp:
  - name: Released
    status: 0
  - name: Tote
    status: 1
  - name: Container
    status: 2
  - name: DeathGrip
    status: 3

ClawRotation:
  - name: InBot
    status: 135
    tolerance: 5.0
  - name: Platform
    status: 227.5
    tolerance: 1.5
  - name: Pick
    status: 70.0
    tolerance: 1.5

ClawRollers:
  - name: In
    status: 2
  - name: Out
    status: 1
  - name: Off
    status: 0
    
ClawSmartRollers:
    
PickBin:
  - smartWait: .25

RegripBin:
  - releaseWait: .25
  - clampWait: .25

GroundToPlatform:
  - liftWait: .25
  
PlatfromToPlacement:

HomeClaw:
  speed: .35

TopClaw:
  speed: -.5

ClawPosition:
  - name: Middle
    target: 195.0
    tolerance: 1.0
  - name: Platform
    target: 180.0
    tolerance: 1.0
  - name: Regrip
    target: 160.0
    tolerance: 1.0

ClawRegripPosition:
  speed: .2

Fingers:
  - name: Hold
    state: 1
  - name: Release
    state: 0

RecieveTote:
  rollerSpeed: -.5

UnloadTote:
  - rollerSpeed: -1

FlapFlappers:

StackTote:
  sensorWait: .25
  waitTime: .25

ArmShuttle:
  first:
    rollerSpeed: 0.8
    flapperSpeed: 0.2
  rest:
    rollerSpeed: 0.1
    flapperSpeed: 0.5

Cancel:
  - name: ArmShuttle

AddTote:

ResetTotes:

Restack:
  lowerWait: .25
  fingerWait: 0
