Claw:
  Ports:
    liftVertical: 6
    liftRotation: 7
    verticalTicks: [6, 7]
    rotationAngle: {Channel: 0, Scale: 360, Offset: 0.0}
    upperLimit: 13
    clampLong: 2
    clampShort: 3
    rollers: 8
    binSensor: 18
  Software:
    liftAngle: {min: 90, max: 270}
    liftHeight: {min: 1, max: 1}
    clearClaw: {min: 0.0, max: 1.0}
  Speeds:
    outward: 0.5
    inward: -0.5
    forward: -0.3
    backward: 0.26
Drive:
  drive:
    L: 1
    R: 0
  encoder:
    L: [2, 3]
    R: [0, 1]
  PID:
    L: {P: 0.02, I: 0, D: 0, F: 0}
    R: {P: 0.02, I: 0, D: 0, F: 0}
  maxRPS: 30
Shuttle:
  Ports:
    toteSensor: 20
    lowerLimit: 10
    upperLimit: 11
    clampPiston: 0
    fingersPiston: 4
    lift:
      motor: 4
      encoder: [4, 5]
      pdp: 15
  Values:
    upSpeed: -0.8
    downSpeed: 0.2
    holdSpeed: -0.1
    maxCurrent: 120.0
