Claw:
  Ports:
    liftVertical: 6
    liftRotation: 7
    verticalTicks: [6, 7]
    rotationAngle: {Channel: 0, Scale: 360, Offset: -48.0}
    upperLimit: {channel: 13, isNPN: true}
    clampLong: 2
    clampShort: 3
    rollers: 8
    binSensor: {channel: 18, isNPN: true}
    homeLimit: {channel: 12, isNPN: false}
  Software:
    clearClaw: {rotate: 149.0, minAngle: 75.0, minHeight: 149}
  Speeds:
    outward: 0.5
    inward: -.8
    up: -1
    down: .5
Drive:
  drive:
    L: 1
    R: 0
  encoder:
    L: [2, 3]
    R: [0, 1]
  platform:
    L: {channel: 15, isNPN: true}
    R: {channel: 14, isNPN: true}
  PID:
    L: {P: 0.02, I: 0, D: 0, F: 0}
    R: {P: 0.02, I: 0, D: 0, F: 0}
  maxRPS: 40
Shuttle:
  Ports:
    toteSensor: {channel: 17, isNPN: true}
    lowerLimit: {channel: 10, isNPN: true}
    upperLimit: {channel: 11, isNPN: true}
    clampPiston: 0
    fingersPiston: 4
    lift:
      motor: 4
      encoder: [4, 5]
      pdp: 15
  Values:
    upSpeed: -0.7
    downSpeed: 0.5
    holdSpeed: -0.1
    speedScale: -.075
    maxCurrent: 120.0
ToteFeed:
  ports:
    rollers: 2
    backSensor: {channel: 16, isNPN: true}
    flappers: 3
    rollerPiston: 1
  flapperSpeed: .5
Otto:
  Ports:
    switch: [23, 22, 21]
