Claw:
  Ports:
    liftVertical: 6
    liftRotation: 7
    verticalTicks: [6, 7]
    rotationAngle: {Channel: 0, Scale: 360, Offset: 0.0}
    upperLimit: 13
    clampLong: 2
    clampShort: 3
    rollers: 8
    binSensor: 18
    homeLimit: 12
  Software:
    clearClaw: {rotate: 175.0, descend: 75.0}
  Speeds:
    outward: 0.5
    inward: -0.5
    forward: -0.3
    backward: 0.26
    up: -.8
    down: .3
Drive:
  drive:
    L: 1
    R: 0
  encoder:
    L: [2, 3]
    R: [0, 1]
  platform:
    L: 15
    R: 14
  PID:
    L: {P: 0.02, I: 0, D: 0, F: 0}
    R: {P: 0.02, I: 0, D: 0, F: 0}
  maxRPS: 30
Shuttle:
  Ports:
    toteSensor: 17
    lowerLimit: 10
    upperLimit: 11
    clampPiston: 0
    fingersPiston: 4
    lift:
      motor: 4
      encoder: [4, 5]
      pdp: 15
  Values:
    upSpeed: -0.5
    downSpeed: 0.2
    holdSpeed: -0.1
    speedScale: -.1
    maxCurrent: 120.0
ToteFeed:
  ports:
    rollers: 2
    backSensor: 16
    flappers: 3
    rollerPiston: 1
  flapperSpeed: .5
