0: # Joystick
  1: WhenPressed HomeShuttle
  2: WhenPressed HomeClaw
  3: WhenPressed TopClaw
  4: WhenPressed PickBin
  5: WhenPressed GroundToPlatform
  6: WhenPressed RegripBin
  7: WhenPressed PlatformToPlacement
  8: WhenPressed ClawRotationPick
  9: WhenPressed ClawPositionRegrip
  10: WhenPressed FingersRelease
  11: WhenPressed StackTote
  12: WhenPressed Restack
1:
  1: WhenPressed ClawClampReleased
  2: WhenPressed ClawClampTote
  3: WhenPressed ClawClampContainer
  4: WhenPressed ClawClampDeathGrip
  5: WhileHeld ClawRollersIn
  6: WhileHeld ClawRollersOut
  7: WhileHeld UnloadTote
  8: WhileHeld FlapFlappers
  9: WhenPressed ArmShuttle
  10: WhenPressed CancelArmShuttle
  11: WhenPressed AddTote
  12: WhenPressed ResetTotes
