0: # Joystick
  1: ToggleWhenPressed ArmShuttle
  2: ToggleWhenPressed $ClawPick
  3: WhileHeld UnloadTote
  4: WhenPressed $GroundToPlatform
  5: WhileHeld ManualClawLiftUp
  6: WhenPressed $RegripBin
  7: WhileHeld ManualClawLiftDown
  8: WhenPressed $PlatformToPlacement
  9: ToggleWhenPressed ClawClampToggle
  10: WhenPressed $Restack
1:
  1: WhenPressed $ClawToPick
  2: WhenPressed $ClawPick
  3: WhenPressed $GroundToPlatform
  4: WhenPressed $RegripBin
  5: WhenPressed $PlatformToPlacement
  6: WhenPressed $Restack
  7: WhenPressed ShuttleRampUp
  8: WhenPressed ShuttleRampDown
  9:
    - WhenPressed ClawForceHome
    - WhenReleased CancelClawForceHome
    - WhenReleased CancelHomeClaw
2:
  1: WhenPressed ClawClampReleased
  3: WhenPressed AddTote
  4: WhenPressed ResetMaxTotes
  5: WhenPressed DecrementMaxTotes
  6: WhenPressed ClawRollersOut
  7: WhileHeld FlapFlappers
  8:
    - WhenPressed ClawForceHome
    - WhenReleased CancelClawForceHome
    - WhenReleased CancelHomeClaw
  9: ToggleWhenPressed ArmShuttle
  10: WhileHeld ManualClawLiftUp
  11: WhileHeld ManualClawLiftDown
  12: WhileHeld UnloadTote
