0: # Joystick
  1: WhenPressed ArmShuttle
  2: WhenPressed $ClawPick
  3: WhileHeld UnloadTote
  4: WhenPressed CancelArmShuttle
  5: WhenPressed $GroundToPlatform
  6: WhenPressed $RegripBin
  7: WhenPressed $Restack
  8: WhenPressed $PlatformToPlacement
  9: WhenPressed ClawClampReleased
  10: WhenPressed ClawClampDeathGrip
1:
  1: WhenPressed $ClawToPick
  2: WhenPressed $ClawPick
  3: WhenPressed $GroundToPlatform
  4: WhenPressed $RegripBin
  5: WhenPressed $PlatformToPlacement
  6: WhenPressed DriveDistanceAutoPick
2:
  1: WhenPressed ClawClampReleased
  2: WhenPressed ResetTotes
  3: WhenPressed AddTote
  4: WhileHeld ClawRollersIn
  5: WhileHeld ClawRollersOut
  6: WhileHeld FlapFlappers
  7:
    - WhenPressed ClawForceHome
    - WhenReleased CancelClawForceHome
    - WhenReleased CancelHomeClaw
  8: WhenPressed ArmShuttle
  9: WhenPressed CancelArmShuttle
  10: WhileHeld ManualClawLiftUp
  11: WhileHeld ManualClawLiftDown
  12: WhileHeld UnloadTote
