0: # Joystick
  1: WhenPressed HomeShuttle
  2: WhenPressed ShuttlePositionUp
  3: WhenPressed ShuttlePositionDown
  4: WhenPressed ShuttleClampOpen
  5: WhenPressed ShuttleClampClose
  6: WhenPressed ClawRotationInBot
  7: WhenPressed ClawRotationPlatform
  8: WhenPressed ClawRotationPick
  9: WhenPressed FingersHold
  10: WhenPressed FingersRelease
1:
  1: WhenPressed ClawClampReleased
  2: WhenPressed ClawClampTote
  3: WhenPressed ClawClampContainer
  4: WhenPressed ClawClampDeathGrip
  5: WhileHeld ClawRollersIn
  6: WhileHeld ClawRollersOut
