0: # Joystick
  1: ToggleWhenPressed ArmShuttle
  2: ToggleWhenPressed $ClawPick
  3: WhileHeld UnloadTote
  4: WhenPressed $GroundToPlatform
  5: WhileHeld ManualClawLiftUp
  6: WhenPressed $RegripBin
  7: WhileHeld ManualClawLiftDown
  8: WhenPressed $PlatformToPlacement
  9: ToggleWhenPressed ClawClampToggle
  10: WhenPressed $Restack
1:
  1: WhenPressed $ClawToPick
  2: ToggleWhenPressed $ClawPick
  3: WhenPressed $GroundToPlatform
  4: WhenPressed $RegripBin
  5: WhenPressed $PlatformToPlacement
  6: ToggleWhenPressed ArmShuttle
  7: WhenPressed $Restack
  8: WhenPressed ClawClampDeathGrip
  9: WhenPressed ClawClampTote
  10: WhenPressed ClawClampContainer
2:
  1: WhenPressed ClawClampReleased
  2: WhenPressed AddTote
  3: WhenPressed ResetTotes
  4: WhenPressed ResetMaxTotes
  5: WhenPressed DecrementMaxTotes
  6: WhenPressed ClawRotationPick
  7: WhenPressed ClawRotationPlatform
  8:
    - WhenPressed ClawForceHome
    - WhenReleased CancelClawForceHome
    - WhenReleased CancelHomeClaw
  9: WhenPressed RollerbedPistonToggle
  10: WhileHeld ManualClawLiftUp
  11: WhileHeld ManualClawLiftDown
  12: WhileHeld UnloadTote
