#########
# DRIVE #
#########

DriveContinuous:
  joystick: 0
  axes:
    left: 1
    right: 3

DriveDistance:
  - name: Auto1
    speed: 0.5
    distance: 4.0
  - name: Auto2_1
    speed: -0.5
    distance: 4.0
  - name: Auto2_2
    speed: -0.5
    distance: 6.0
  - name: Auto5_1
    speed: 0.5
    distance: 0.25
  - name: Auto5_2
    speed: -0.5
    distance: 7.0
  - name: CatchCan
    speed: -.5
    distance: 0.05
  - name: GetCans
    speed: 1.0
    distance: 2.5
  - name: EscapeCan
    speed: 0.4
    distance: 4.5

DriveRotate:
  - name: Auto2
    speed: .65
    angle: 90.0
    tolerance: 2.0
    slowAngle: 25.0
    slowFactor: .85
  - name: Auto3
    speed: .85
    angle: 45.0
    tolerance: 2.0
    slowAngle: 25.0
    slowFactor: .85
  - name: Auto6
    speed: .8
    angle: 90.0
    tolerance: 0.5
    slowAngle: 25.0
    slowFactor: .7
  - name: Auto7_1
    speed: .65
    angle: -90.0
    tolerance: .5
    slowAngle: 25.0
    slowFactor: .85
  - name: Auto7_2
    speed: .65
    angle: -115.0
    tolerance: 2.0
    slowAngle: 25.0
    slowFactor: .85
  - name: Auto7_3
    speed: .85
    angle: -45.0
    tolerance: 2.0
    slowAngle: 25.0
    slowFactor: .85

DriveStraight:
  - name: Auto3_1
    speed: -0.5
    angle: -10.0
    distance: 5.0
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto3_2
    speed: 0.5
    angle: 10.0
    distance: 3.0
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto3_3
    speed: -0.5
    angle: -10.0
    distance: 3.0
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto3_4
    speed: 0.5
    angle: 45.0
    distance: 1.0
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto6
    speed: 1.0
    angle: 90.0
    distance: 8.5
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto7_1
    speed: 0.65
    angle: -90
    distance: 16.0
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto7_2
    speed: -.4
    angle: -115.0
    distance: 2
    PID: {P: 0, I: 0, D: 0, F: 0}

DriveZach:
  - name: Test1
    speed: 0.25
    distance: 3.0
    startAngle: 0.0
    endAngle: 45.0
  - name: Test2
    speed: 0.25
    distance: 3.0
    startAngle: 45.0
    endAngle: 0.0
    ramp:
      distance: 1.0
      power: 2.0
  - name: Auto6
    speed: .5
    distance: 10.25
    startAngle: 90
    endAngle: -90

ResetAngle:

###########
# SHUTTLE #
###########

Fingers:
  - name: Hold
    state: 1
  - name: Release
    state: 0

$FixJam:
  - ShuttlePositionUnload
  - ShuttleRampDown

HomeShuttle:
  speed: .4

LackOfStack:
  # No config

$Restack:
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttlePositionUnload
  - FingersRelease
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

SetDesiredTotes:
  - name: Two
    number: 2
  - name: Three
    number: 3
  - name: Four
    number: 4
  - name: Five
    number: 5
  - name: Six
    number: 6

ShuttleClamp:
  - name: Open
  - name: Close

ShuttleDown:
  ticks: 50
  tolerance: 10
  speed: 0.25

ShuttleHold:
  speed: -.4
  time: .5

$ShuttleInit:
  - FingersRelease
  - HomeShuttle
  - ShuttleClampOpen

ShuttlePosition:
  - name: Unload
    ticks: 350
  - name: Unstack
    ticks: 460

ShuttleRamp:
  - name: Up
    ticks: 699
    rampFactor: .2
    rampDistance: 150
  - name: Down
    ticks: -5
    rampFactor: .2
    rampDistance: 150

$StackTote:
  - FingersHold
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: .25
  - ShuttleRampUp
  - UpdateTotesRatcheted
  - name: WaitCommand
    time: 0.125
  - ShuttleClampOpen
  - ShuttleRampDown

ToteDictator:
  samples:
    bottom: 13
    shuttle: 6

$Unstack:
  - ShuttleClampOpen
  - ShuttlePositionUnstack
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttleRampUp
  - FingersRelease
  - ShuttleHold
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

UpdateTotesRatcheted:
  # No config

########
# CLAW #
########

ClawClamp:
  - name: Released
    status: 0
  - name: Left
    status: 1
  - name: Right
    status: 2
  - name: DeathGrip
    status: 3

ClawClampToggle:
  # No config

ClawHomeTop:
  speed: -.4

ClawEstablishHome:
  # No config

ClawRegripPosition:
  speed: .2

ClawSmartRollers:
  waitTime: .25

ClawToAngle:
  - name: Front
    angle: front
    speed: -.50
    holdSpeed: -.20
    ramp:
      distance: 50
      factor: .35
    minimumHeight: 160
  - name: Back
    angle: back
    speed: .50
    holdSpeed: .20
    ramp:
      distance: 50
      factor: .30
    minimumHeight: 160

ClawToHeight:
  - name: Home
    height: -1.0
    ramp: {distance: 50.0, factor: .25}
    speed: 1.0
    requiredAngle: front
  - name: Top
    height: 240
    ramp: {distance: 20.0, factor: .25}
    speed: 1.0
    requiredAngle: neither
  - name: Middle
    height: 196
    ramp: {distance: 20.0, factor: .25}
    speed: 1.0
    requiredAngle: neither
  - name: Platform
    height: 180
    ramp: {distance: 0.0, factor: 0.0}
    speed: .25
    requiredAngle: back
  - name: Regrip
    height: 149
    ramp: {distance: 0.0, factor: 0.0}
    speed: .25
    requiredAngle: back

ClawUnload:

$ClawToPick:
  - ClawToAngleFront
  - ClawToHeightHome

$GroundToPlatform:
  - ClawClampDeathGrip
  - ClawToHeightMiddle
  - ClawToAngleBack
  - name: WaitCommand
    time: 0.5
  - ClawToHeightPlatform

ManualClawLift:
  - name: "Up"
    speed: -.75
  - name: "Down"
    speed: .25

$PickBin:
  - ClawClampRight
  - ClawSmartRollers
  - name: WaitCommand
    time: 0.25
  - ClawClampDeathGrip

$ClawPick:
  - $ClawToPick
  - $PickBin

$PickUpMoveToPlatform:
  - $PickBin
  - name: WaitCommand
    time: 0.25
  - $GroundToPlatform

$RegripBin:
  - name: WaitCommand
    time: 0.50
  - ClawClampReleased
  - name: WaitCommand
    time: 0.25
  - ClawToHeightRegrip
  - name: WaitCommand
    time: 0.25
  - ClawClampDeathGrip
  - ClawSmartRollers

#########
# THIEF #
#########

ThiefGrabber:
  - name: In
    status: 0
  - name: Out
    status: 1

ThiefToggle:

#############
# TOTE FEED #
#############

BumpBottomTote:
  rollerSpeed: -0.5
  time: 0.25

HoldBottomTote:
  rollerSpeed:
    slow: 0.1
    fast: 0.5

IntakeTotes:
  flapperSpeed: .9

RecieveBottomTote:
  flapperSpeed: 0.35
  rollerSpeed: 0.8

UnloadTote:
  rollerSpeed: -1
  flapperSpeed: -1

########
# AUTO #
########

# Test auto
$Auto0:
  - ResetAngle
  - DriveZachAuto6

# Drive and pick can at right slot
$Auto1:
  - ResetAngle
  - name: DriveDistanceAuto1
    execution: Parallel
  - $ClawPick
  - $GroundToPlatform

# 3309 auto: pick middle can from a 45 degree angle and get behind the scoring platform
$Auto2:
  - ResetAngle
  - $ClawPick
  - name: $GroundToPlatform
    execution: Parallel
  - DriveDistanceAuto2_1
  - DriveRotateAuto2
  - DriveDistanceAuto2_2

# Start on platform with can, drive to right slot
$Auto3:
  - ResetAngle
  - ClawHomeTop
  - ClawToHeightPlatform
  - DriveStraightAuto3_1
  - DriveStraightAuto3_2
  - DriveStraightAuto3_3
  - DriveRotateAuto3
  - DriveStraightAuto3_4

$Auto4:
  - ResetAngle

# 624 auto: Pick the left can and get out of there
$Auto5:
  - name: DriveDistanceAuto5_1
    execution: Parallel
  - $ClawPick
  - name: DriveDistanceAuto5_2
    execution: Parallel
  - $GroundToPlatform

# Canburgler auto
$Auto6:
  - ThiefGrabberOut
  - name: ResetAngle
    execution: Parallel
  - name: $ClawToPick
    execution: Parallel
  - name: DriveDistanceCatchCan
    execution: Parallel
  # - name: WaitCommand
    # time: 0.4
  # - ThiefGrabberIn
  # - name: WaitCommand
    # time: 0.3
  # - ThiefGrabberOut
  - name: WaitCommand
    time: 2.0
  - DriveDistanceGetCans
  - ThiefGrabberIn
  - DriveDistanceEscapeCan
  - DriveRotateAuto6
  - DriveStraightAuto6
  - DriveZachAuto6

# Pick the left can and drive to the right slot
$Auto7:
  - ResetAngle
  - $ClawPick
  - name: $GroundToPlatform
    execution: Parallel
  - DriveRotateAuto7_1
  - DriveStraightAuto7_1
  - DriveRotateAuto7_2
  - DriveStraightAuto7_2
  - DriveRotateAuto7_3
