#########
# DRIVE #
#########

DriveContinuous:
  joystick: 0
  axes:
    left: 1
    right: 3

DriveDistance:
  - name: AutoPick
    speed: 0.45
    distance: 1.0
  - name: AutoPickLong
    speed: 0.45
    distance: 4.0
  - name: AutoPickShort
    speed: 0.45
    distance: 1.0
  - name: AutoBack
    speed: -0.45
    distance: 7.0
  - name: AutoBackLong
    speed: -0.45
    distance: 8.0
  - name: AutoThreeDistance
    speed: 0.45
    distance: 8.0
  - name: AutoFourDistance
    speed: 0.45
    distance: 1.0
  - name: Auto2
    speed: -0.75
    distance: 4.0
  - name: Auto2_2
    speed: -0.75
    distance: 6.0
  - name: GetCans
    speed: 1.0
    distance: 3.5
  - name: AutoBackShort
    speed: -.50
    distance: 0.25
  - name: EscapeCan
    speed: 0.50
    distance: 2.0

DriveArc:
  - name: Auto6
    speed: .5
    angle: 0.0
    distance: 6.0
    degreesPerFoot: 15.0
    PID: {P: .05, I: .00, D: 0, F: 0}

DriveRotate:
  - name: Auto6
    speed: .75
    angle: 90.0
    tolerance: .5
    slowAngle: 25.0
    slowFactor: .75
  - name: Auto7_1
    speed: .75
    angle: -87.0
    tolerance: .5
    slowAngle: 25.0
    slowFactor: .75
  - name: Auto7_2
    speed: .75
    angle: -115.0
    tolerance: 1.0
    slowAngle: 25.0
    slowFactor: .75
  - name: Auto7_3
    speed: .9
    angle: -45.0
    tolerance: 1.0
    slowAngle: 25.0
    slowFactor: .75
  - name: Auto2
    speed: .85
    angle: 90.0
    tolerance: .5
    slowAngle: 25.0
    slowFactor: .9

DriveStraight:
  - name: Auto6
    speed: 1.0
    angle: 90.0
    distance: 12.0
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto7_1
    speed: 1.0
    angle: -87
    distance: 16.0
    PID: {P: .05, I: .00, D: 0, F: 0}
  - name: Auto7_2
    speed: -.40
    angle: -115.0
    distance: 2.5
    PID: {P: 0, I: 0, D: 0, F: 0}

ResetAngle:

###########
# SHUTTLE #
###########

Fingers:
  - name: Hold
    state: 1
  - name: Release
    state: 0

$FixJam:
  - ShuttlePositionUnload
  - ShuttleRampDown

HomeShuttle:
  # No config

LackOfStack:
  # No config

$Restack:
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttlePositionUnload
  - FingersRelease
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

SetDesiredTotes:
  - name: Two
    number: 2
  - name: Three
    number: 3
  - name: Four
    number: 4
  - name: Five
    number: 5
  - name: Six
    number: 6

ShuttleClamp:
  - name: Open
  - name: Close

ShuttleDown:
  ticks: 50
  tolerance: 10
  speedMul: 0.0

ShuttleHold:
  speed: -.4
  time: .5

$ShuttleInit:
  - FingersRelease
  - ShuttleClampOpen
  - HomeShuttle

ShuttlePosition:
  - name: Unload
    ticks: 350
  - name: Unstack
    ticks: 460

ShuttleRamp:
  - name: Up
    ticks: 697
    tolerance: 4
    rampFactor: .75
    rampDistance: 300
  - name: Down
    ticks: 0
    tolerance: 4
    rampFactor: .2
    rampDistance: 300

$StackTote:
  - FingersHold
  - ShuttleClampOpen
  - ShuttleRampDown
  - ShuttleClampClose
  - name: WaitCommand
    time: .25
  - ShuttleRampUp
  - UpdateTotesRatcheted
  - name: WaitCommand
    time: .25
  - ShuttleClampOpen
  - ShuttleRampDown

ToteDictator:
  samples: 6

$Unstack:
  - ShuttleClampOpen
  - ShuttlePositionUnstack
  - ShuttleClampClose
  - name: WaitCommand
    time: 0.25
  - ShuttleRampUp
  - FingersRelease
  - ShuttleHold
  - ShuttleDown
  - ShuttleRampDown
  - ShuttleClampOpen

UpdateTotesRatcheted:
  # No config

########
# CLAW #
########

ClawClamp:
  - name: Released
    status: 0
  - name: Left
    status: 1
  - name: Right
    status: 2
  - name: DeathGrip
    status: 3

ClawClampToggle:
  # No config

ClawEstablishHome:
  # No config

ClawRegripPosition:
  speed: .2

ClawSmartRollers:
  waitTime: .25

ClawToAngle:
  - name: Front
    angle: front
    speed: -.50
    holdSpeed: -.20
    ramp:
      distance: 50
      factor: .30
    minimumHeight: 160
  - name: Back
    angle: back
    speed: .50
    holdSpeed: .20
    ramp:
      distance: 50
      factor: .30
    minimumHeight: 160

ClawToHeight:
  - name: Home
    height: 0.0
    ramp: {distance: 50.0, factor: .15}
    speed: 1.0
    requiredAngle: front
  - name: Top
    height: 247.0
    ramp: {distance: 20.0, factor: .25}
    speed: 1.0
    requiredAngle: neither
  - name: Middle
    height: 196
    ramp: {distance: 20.0, factor: .25}
    speed: 1.0
    requiredAngle: neither
  - name: Platform
    height: 180
    ramp: {distance: 0.0, factor: 0.0}
    speed: .25
    requiredAngle: back
  - name: Regrip
    height: 156
    ramp: {distance: 0.0, factor: 0.0}
    speed: .25
    requiredAngle: back

ClawUnload:

$ClawToPick:
  - ClawToAngleFront
  - ClawToHeightHome

$GroundToPlatform:
  - ClawClampDeathGrip
  - ClawToHeightMiddle
  - ClawToAngleBack
  - name: WaitCommand
    time: 0.5
  - ClawToHeightPlatform

ManualClawLift:
  - name: "Up"
    speed: -.75
  - name: "Down"
    speed: .25

$PickBin:
  - ClawClampRight
  - ClawSmartRollers
  - name: WaitCommand
    time: 0.25
  - ClawClampDeathGrip

$ClawPick:
  - $ClawToPick
  - $PickBin

$PickUpMoveToPlatform:
  - $PickBin
  - name: WaitCommand
    time: 0.25
  - $GroundToPlatform

$RegripBin:
  - name: WaitCommand
    time: 0.50
  - ClawClampReleased
  - name: WaitCommand
    time: 0.25
  - ClawToHeightRegrip
  - name: WaitCommand
    time: 0.25
  - ClawClampDeathGrip
  - ClawSmartRollers

#########
# THIEF #
#########

ThiefGrabber:
  - name: In
    status: 0
  - name: Out
    status: 1

ThiefToggle:

#############
# TOTE FEED #
#############

BumpBottomTote:
  rollerSpeed: -0.5
  time: 0.25

HoldBottomTote:
  rollerSpeed: 0.25

IntakeTotes:
  flapperSpeed: .9

RecieveBottomTote:
  flapperSpeed: 0.35
  rollerSpeed: 0.8

UnloadTote:
  rollerSpeed: -1
  flapperSpeed: -1

########
# AUTO #
########

$Auto0:
  - ResetAngle

$Auto1:
  - ResetAngle
  - name: DriveDistanceAutoPickLong
    execution: Parallel
  - $ClawPick
  - $GroundToPlatform

$Auto2DriveSequence:
  - name: WaitCommand
    time: 1.0
  - DriveDistanceAuto2
  - DriveRotateAuto2
  - DriveDistanceAuto2_2

$Auto2:
  - ResetAngle
  - $ClawToPick
  - name: $Auto2DriveSequence
    execution: Parallel
  - ClawSmartRollers
  - $GroundToPlatform

$Auto3:
  - name: DriveDistanceAutoThreeDistance
    execution: Parallel
  - $ClawPick
  - $GroundToPlatform

$Auto4:
  - name: DriveDistanceAutoFourDistance
    execution: Parallel
  - $ClawPick
  - $GroundToPlatform

$Auto5:
  - name: DriveDistanceAutoPickShort
    execution: Parallel
  - $ClawPick
  - name: DriveDistanceAutoBack
    execution: Parallel
  - $GroundToPlatform

$Auto6:
  - ThiefGrabberOut
  - name: ResetAngle
    execution: Parallel
  - name: $ClawToPick
    execution: Parallel
  - name: WaitCommand
    time: 0.4
  - ThiefGrabberIn
  - name: WaitCommand
    time: 0.3
  - ThiefGrabberOut
  - name: WaitCommand
    time: 0.2
  - DriveDistanceGetCans
  - ThiefGrabberIn
  - DriveDistanceEscapeCan
  - DriveRotateAuto6
  - DriveStraightAuto6

$Auto7:
  - ResetAngle
  - $ClawPick
  - name: $GroundToPlatform
    execution: Parallel
  - DriveRotateAuto7_1
  - DriveStraightAuto7_1
  - DriveRotateAuto7_2
  - DriveStraightAuto7_2
  - DriveRotateAuto7_3
