Claw:
  Ports:
    lift:
      motor: 6
      encoder: [6, 7]
    rotation:
      motor: 7
      encoder: {Channel: 0, Scale: 360, Offset: 23.0}
    limits:
      home: {channel: 12, isNPN: false}
      top: {channel: 13, isNPN: true}
    clamp: {left: 3, right: 2}
    rollers: 8
    binSensor: {channel: 18, isNPN: true}
  Software:
    heightTolerance: 3.0
    angles:
      tolerance: 15.0
      front: 70.0
      back: 235.0
Drive:
  drive:
    L: 1
    R: 0
  encoder:
    L: [2, 3]
    R: [0, 1]
  platform:
    L: {channel: 15, isNPN: true}
    R: {channel: 14, isNPN: true}
  PID:
    L: {P: 0.02, I: 0, D: 0, F: 0}
    R: {P: 0.02, I: 0, D: 0, F: 0}
  maxRPS: 40
Shuttle:
  Ports:
    toteSensor: {channel: 17, isNPN: true}
    lowerLimit: {channel: 10, isNPN: true}
    upperLimit: {channel: 11, isNPN: true}
    clampPiston: 0
    fingersPiston: 4
    lift:
      motor: 4
      encoder: [4, 5]
      pdp: 15
  Values:
    upSpeed: -0.7
    downSpeed: 0.5
    holdSpeed: -0.1
    speedScale: -.075
    maxCurrent: 120.0
ToteFeed:
  ports:
    rollers: 2
    backSensor: {channel: 16, isNPN: true}
    flappers: 3
Otto:
  Ports:
    switch: [23, 22, 21]
  Camera:
    name: cam2
    exposure: auto
    brightness: 50
Thief:
  port: 5
