0: # Joystick
  1: ToggleWhenPressed ToteDictator
  2: ToggleWhenPressed $ClawPick
  3: WhileHeld UnloadTote
  4: WhenPressed $GroundToPlatform
  5: WhileHeld ManualClawLiftUp
  6: WhenPressed $RegripBin
  7: WhileHeld ManualClawLiftDown
  8: WhenPressed $PlatformToPlacement
  9: WhenPressed ClawClampToggle
  10: WhenPressed $Restack
1:
  1: WhenPressed SetDesiredTotesTwo
  2: WhenPressed SetDesiredTotesThree
  3: WhenPressed SetDesiredTotesFour
  4: WhenPressed SetDesiredTotesFive
  5: WhenPressed SetDesiredTotesSix
  6: ToggleWhenPressed ToteDictator
  7: WhenPressed ThiefGrabberOut
  8: WhenPressed ClawClampDeathGrip
  9: WhenPressed ClawClampTote
  10: WhenPressed ClawClampContainer
2:
  1: WhenPressed ClawClampReleased
  2: WhenPressed $ClawToPick
  3: ToggleWhenPressed $ClawPick
  4: WhenPressed $GroundToPlatform
  5: WhenPressed $RegripBin
  6: WhenPressed ClawToAngleFront
  7: WhenPressed ClawToAngleBack
  8: WhenPressed $PlatformToPlacement
  9: WhenPressed $FixJam
  10: WhileHeld ManualClawLiftUp
  11: WhileHeld ManualClawLiftDown
  12: WhileHeld UnloadTote
